version: '3.8'
services:
  app:
    image: your-image-name
    container_name: your-container-name
    ports:
      - '8000:80'
    environment:
      - ENV_VAR_NAME=value
    volumes:
      - ./data:/data
